### ISSUE TITLE
Merge with Ko7 PHP 8.3 branch

### ISSUE THREAD

**Issue by timhj** [Wmcurr/Kohana-php-8.3#1]
Great work on doing this alone. The official KO7 repo has been working on an 8.3 branch for a while (https://github.com/koseven/koseven/tree/php8.3).

Sounds like you've put a lot of effort into the 8.3 compliance, it would be great for you to do a diff on the branch and PR any additional changes you've made back to the koseven branch. It'll make upgrading your framework going forwards easier too.

**Comment by Wmcurr** [comment]
Hello,

I'm sorry, but I don't have the time to provide detailed descriptions of
what has been changed. I'm only getting about 4 hours of sleep per night
and am currently in the process of completely rewriting the Kohana
framework.

Thank you for your understanding.

чт, 15 авг. 2024 г., 04:42 timhj ***@***.***>:

**Comment by timhj** [comment]
No worries at all. You might get more sleep if you worked with the rest of the maintainers over at https://github.com/koseven/koseven and shared the load instead of going it alone though. There's already a PHP 8.3 compatible version on the main repository.

I hope your sleep situation improves.

**Comment by Wmcurr** [comment]
https://t.me/kosevenru I'm in the group as well, so feel free to message me
there.

чт, 15 авг. 2024 г., 06:50 timhj ***@***.***>:

**Comment by timhj** [comment]
Thanks - I had a look at the telegram group but as an english speaker it's not much use to me!

**Comment by pronego-info** [comment]
Great work so far! We’ll take a look at this on our end at koeight.dev as well and are happy to help.
